### ISSUE TITLE
upcoming zig-0.11.0-dev.3132+465272921

### ISSUE THREAD

**Issue by motiejus** [marler8997/zig-unofficial-releases#11]
Hi Jonathan,

It's been around 2 weeks since the last "unrelease", and I am about to cut hermetic_cc_toolchain v2. I created a mirror request to save you a little bit of trouble: https://github.com/bazelbuild/bazel/issues/18397

**Comment by marler8997** [comment]
Thanks, busy weekend didn't get around to doing the release yet.  Started it with the links ready here: https://github.com/marler8997/zig-unofficial-releases/pull/12
