### ISSUE TITLE
Provide binary download links

### ISSUE THREAD

**Issue by emidoots** [marler8997/zig-unofficial-releases#3]
I like what you're doing here a lot.

It'd be nice to include binary download links for the versions, though, e.g. like I do in Mach here:

https://github.com/hexops/mach/tree/044288e5a08b439796ed8a64e8c94956157835ca#supported-zig-version

Right now since that doesn't exist its a bit hard to link random users to this repo, since they may not know how to build from source etc.

**Comment by motiejus** [comment]
Mentioned this on IRC, but just to be on the safe side.

Zig nightlies are downloadable from ziglang.org/builds for ~3 months. I learned this the hard way.

When I need to mirror a Zig nightly build, I ask Google to mirror it for me. Zig is "part of" Bazel ecosystem now, so we have the full right to do it. Here is an example: https://github.com/bazelbuild/bazel/issues/17635

I am upgrading Zig SDK in bazel-zig-cc every once in a while -- and when I do, I add a mirror there. I would be happy to coordinate with you, @marler8997 , when you are cutting a release: we could add a Bazel mirror next to the ones you do now.

**Comment by motiejus** [comment]
For the record, I will be upgrading Zig SDK in bazel-zig-cc in about a week. Any release since today should work for me. We can also do it this way -- when I upgrade Zig SDK, I take your "biweekly" release, mirror it, and submit a PR adding the alternative links.

**Comment by marler8997** [comment]
I've been doing these unofficial releases every 2 weeks. Will we be able to mirror that often?

**Comment by motiejus** [comment]
> I've been doing these unofficial releases every 2 weeks. Will we be able to mirror that often?

Yes, I am not aware of any practical limits. Here is how to submit a mirror request:

1. Open https://github.com/bazelbuild/bazel/issues/new/choose
2. Select "Mirror request"
3. Enter URLs, like in https://github.com/bazelbuild/bazel/issues/17635. You may title the issue `zig <version>` for consistency, like `zig 0.11.0-dev.1796+c9e02d3e6`.
4. Wait a "business hour" (AFAIK someone oncall at Google gets a low-urgency notification).
5. The artifact gets mirrored.

**Comment by motiejus** [comment]
For the record, the release process of `hermetic_cc_toolchain`  points to your repository. It's quite convenient to have a version to choose from that is more "stable" than the one from a few hours ago. :)

https://github.com/uber/hermetic_cc_toolchain/wiki/Release-Process

And the `v2.0.0-rc1` uses the latest "unofficial release": https://github.com/uber/hermetic_cc_toolchain/releases/tag/v2.0.0-rc1

Thank you!
